# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

class TestOfd():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_ofd(self):
        self.driver.get("https://cluster-test.taxcom.ru/")
        self.driver.set_window_size(1920, 1080)
        self.driver.find_element(By.LINK_TEXT, "ОФД: отправка электронных чеков").click()
        self.driver.find_element(By.XPATH, "(//a[contains(@href, \'#\')])[12]").click()

        time.sleep(3)
        self.driver.find_element(By.ID, "byPhone").click()
        time.sleep(3)
        self.driver.find_element(By.NAME, "form_text_796").click()
        self.driver.find_element(By.NAME, "form_text_796").send_keys("test")
        self.driver.find_element(By.NAME, "form_text_797").click()
        self.driver.find_element(By.NAME, "form_text_797").send_keys("1111111111")
        self.driver.find_element(By.NAME, "form_text_798").click()
        self.driver.find_element(By.NAME, "form_text_798").send_keys("693714798909")
        self.driver.find_element(By.ID, "submitOfdConnect").click()

